os:
  - windows
  - linux
  - osx

language: cpp
# install: make <command>

compiler:
  - clang
  - g++


before_script:
  ############################################################################
  # Set the git identity (for pushing the documentation and the benchmarks)
  ############################################################################
  # - git config --global user.name "Travis bot"
  # - git config --global user.email "<>"

  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  # - cd ${TRAVIS_BUILD_DIR}
  # - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})


script:

jobs:
  include:
    - stage: test
      name: "compile tests"
      script: make compile_tests
    - name: "run display_game"
      script: ./builds/display_game
    - name: "run display_game"
      script: ./builds/compute_multiple_gens