name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: compile main
      run: make main

  debug_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: compile main
      run: make main DEBUG=1

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: compile tests
      run: make compile_tests
    - name: test display_game
      run: ./builds/display_game
